


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json

###
GET /api/v1/security/login
Host: localhost:9000
Accept: text/plain
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/security/logout
Host: localhost:9000
Accept: text/plain



### Identity Requests



###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "authority": "ADMIN",
    "username": "burgvv",
    "password": "burgasvv",
    "email": "burgasvv@gmail.com",
    "phone": "+79139054523",
    "status": true,
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич"
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "authority": "USER",
    "username": "zagor",
    "password": "zagor",
    "email": "zagor@gmail.com",
    "phone": "+79526324578",
    "status": true,
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич"
}

###
POST /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "id": "159514d2-05ec-4386-8df4-6c0c3aa69d8c",
    "username": "burgasvv"
}

###
POST /api/v1/identities/delete?identityId=72bf90d3-dda8-470a-b2f1-301cdfbb100c
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

###
GET /api/v1/identities/by-id?identityId=159514d2-05ec-4386-8df4-6c0c3aa69d8c
Host: localhost:9000
Accept: application/json

###
GET /api/v1/identities/by-id?identityId=8376abf9-9437-4f15-8432-1a7a76f42556
Host: localhost:9000
Accept: application/json

###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
PUT /api/v1/identities/remove-files?identityId=159514d2-05ec-4386-8df4-6c0c3aa69d8c
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "fileIds": ["482c4af3-dfa7-44dc-b8a2-341c719ee49f"]
}

###
PUT /api/v1/identities/make-preview-image?identityId=159514d2-05ec-4386-8df4-6c0c3aa69d8c&imageId=31b6446e-5d97-4bb1-8657-935d0ac72bb6
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab
Authorization: Basic burgasvv@gmail.com burgasvv

###
PUT /api/v1/identities/add-contact?identityId=159514d2-05ec-4386-8df4-6c0c3aa69d8c&contactId=8376abf9-9437-4f15-8432-1a7a76f42556
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab
Authorization: Basic burgasvv@gmail.com burgasvv

###
PUT /api/v1/identities/remove-contact?identityId=159514d2-05ec-4386-8df4-6c0c3aa69d8c&contactId=8376abf9-9437-4f15-8432-1a7a76f42556
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab
Authorization: Basic burgasvv@gmail.com burgasvv



### Dialogue Requests



###
GET /api/v1/dialogues/by-id?dialogueId=2c7b4569-c9b5-4f13-8e78-9502eee76dfc
Host: localhost:9000
Accept: application/json

###
DELETE /api/v1/dialogues/delete?dialogueId=2c7b4569-c9b5-4f13-8e78-9502eee76dfc
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab



### Dialogue-Message Requests



###
GET /api/v1/dialogue-messages/by-id?dialogueMessageId=b05f8964-f291-45b4-b875-048697bdade1
Host: localhost:9000
Accept: application/json



###
POST /api/v1/chats/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "name": "First Chat",
    "description": "Описание чата First Chat",
    "opened": true,
    "adminId": "159514d2-05ec-4386-8df4-6c0c3aa69d8c"
}

###
POST /api/v1/chats/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "id": "7a430ac4-3274-4723-b5ce-e17eced40b85",
    "adminId": "6f525500-1832-41b2-80c8-151c466854b8"
}

###
PUT /api/v1/chats/join
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "groupId": "7a430ac4-3274-4723-b5ce-e17eced40b85",
    "applicantId": "6f525500-1832-41b2-80c8-151c466854b8"
}

###
PUT /api/v1/chats/out
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "groupId": "7a430ac4-3274-4723-b5ce-e17eced40b85",
    "applicantId": "6f525500-1832-41b2-80c8-151c466854b8"
}

###
PUT /api/v1/chats/remove-admin-status
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "groupId": "7a430ac4-3274-4723-b5ce-e17eced40b85",
    "applicantId": "6f525500-1832-41b2-80c8-151c466854b8"
}

###
GET /api/v1/chats/by-id?chatId=7a430ac4-3274-4723-b5ce-e17eced40b85
Host: localhost:9000
Accept: application/json



### Chat-Message Requests



###
GET /api/v1/chat-messages/by-id?chatMessageId=6378148f-a1b5-4264-a4ef-bfc718b2cb79
Host: localhost:9000
Accept: application/json



### Community Requests



###
POST /api/v1/communities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "name": "Community First Test",
    "description": "Описание сообщества Community First",
    "opened": true,
    "adminId": "159514d2-05ec-4386-8df4-6c0c3aa69d8c"
}

###
POST /api/v1/communities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "id": "fde292e5-2e1a-4049-88f4-ab57e9249ef0",
    "adminId": "6f525500-1832-41b2-80c8-151c466854b8"
}

###
GET /api/v1/communities/by-id?communityId=fde292e5-2e1a-4049-88f4-ab57e9249ef0
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/communities/join
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "groupId": "fde292e5-2e1a-4049-88f4-ab57e9249ef0",
    "applicantId": "6f525500-1832-41b2-80c8-151c466854b8"
}

###
PUT /api/v1/communities/out
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "groupId": "fde292e5-2e1a-4049-88f4-ab57e9249ef0",
    "applicantId": "6f525500-1832-41b2-80c8-151c466854b8"
}

###
PUT /api/v1/communities/remove-admin-status
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 7f7eeddc-4fbc-4c08-bfa4-c6031ffa89ab

{
    "groupId": "fde292e5-2e1a-4049-88f4-ab57e9249ef0",
    "applicantId": "6f525500-1832-41b2-80c8-151c466854b8"
}